# Generated by Django 6.0.3 on 2026-04-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patientprofile_age_patientprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
