# Generated by Django 6.0.3 on 2026-04-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_timeslot_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
